import "./globals.css";
import { Roboto } from "next/font/google";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  
});

export const metadata = {
  title: "Ignite Feed",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="bg-gray-950" lang="pt-BR">
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
